# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database:  sample_app_test
  pool: 5


